# # # # # # # # # # # # # # # # # # # # # # # # # #
#  ╔═╗╔═╗╔═╗╦  ╦╔═╗╦ ╦╔═╗╦═╗ ┬ ┬┌┬┐┬              #
#  ╠═╣╠═╝╠═╝╚╗╔╝║╣ ╚╦╝║ ║╠╦╝ └┬┘││││              #
#  ╩ ╩╩  ╩   ╚╝ ╚═╝ ╩ ╚═╝╩╚═o ┴ ┴ ┴┴─┘            #
#                                                 #
# This file configures Appveyor CI.               #
# (i.e. how we run the tests on Windows)          #
#                                                 #
# https://www.appveyor.com/docs/lang/nodejs-iojs/ #
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

# Install and run MongoDB
services:
  - mongodb

# Install scripts.
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - choco install make
  # Install declared dependencies
  - npm install

#  Test scripts.
test_script:
  # Output Node and NPM version info.
  # (Presumably just in case Appveyor decides to try any funny business?
  #  But seriously, always good to audit this kind of stuff for debugging.)
  - node --version
  - npm --version
  # Run the actual tests.
  - npm test

build: off